MMCore: ConfigGroupBase< T > Class Template Reference
ConfigGroupBase< T > Class Template Reference
#include <ConfigGroup.h>
Public Member Functions
void Define (const char *configName)
void Define (const char *configName, const char *deviceLabel, const char *propName, const char *value)
T * Find (const char *configName)
bool Rename (const char *oldConfigName, const char *newConfigName)
bool Delete (const char *configName)
bool Delete (const char *configName, const char *deviceLabel, const char *propName)
std::vector< std::string > GetAvailable () const
bool IsEmpty ()
Protected Attributes
std::map< std::string, T > configs_
Detailed Description
template<class T>
class ConfigGroupBase< T >
Encapsulates a collection (map) of user-defined presets.
Member Function Documentation
Define() [1/2]
template<class T > void ConfigGroupBase< T >::Define (const char * configName) inline
Defines a new preset.
Define() [2/2]
template<class T > void ConfigGroupBase< T >::Define (const char * configName, const char * deviceLabel, const char * propName, const char * value) inline
Defines a new preset.
Delete() [1/2]
template<class T > bool ConfigGroupBase< T >::Delete (const char * configName) inline
Deletes a preset by name.
Referenced by CMMCore::unloadAllDevices().
Delete() [2/2]
template<class T > bool ConfigGroupBase< T >::Delete (const char * configName, const char * deviceLabel, const char * propName) inline
Deletes a preset property by name.
Find()
template<class T > T* ConfigGroupBase< T >::Find (const char * configName) inline
Finds preset by name.
Referenced by CMMCore::getPixelSizeUm().
GetAvailable()
template<class T > std::vector<std::string> ConfigGroupBase< T >::GetAvailable () const inline
Returns a list of available configurations.
Referenced by CMMCore::getAvailablePixelSizeConfigs(), and CMMCore::unloadAllDevices().
Rename()
template<class T > bool ConfigGroupBase< T >::Rename (const char * oldConfigName, const char * newConfigName) inline
Renames a preset (addressed by old name).
The documentation for this class was generated from the following file:
ConfigGroup.h