MMCore: ConfigGroupCollection Class Reference
ConfigGroupCollection Class Reference
#include <ConfigGroup.h>
Public Member Functions
void Define (const char *groupName, const char *configName)
void Define (const char *groupName, const char *configName, const char *deviceLabel, const char *propName, const char *value)
bool Define (const char *groupName)
Configuration * Find (const char *groupName, const char *configName)
bool isDefined (const char *groupName)
bool RenameConfig (const char *groupName, const char *oldConfigName, const char *newConfigName)
bool Delete (const char *groupName, const char *configName, const char *deviceLabel, const char *propName)
bool Delete (const char *groupName, const char *configName)
bool Delete (const char *groupName)
bool RenameGroup (const char *oldGroupName, const char *newGroupName)
std::vector< std::string > GetAvailableGroups () const
std::vector< std::string > GetAvailableConfigs (const char *groupName) const
void Clear ()
Detailed Description
Encapsulates a collection of preset groups.
Member Function Documentation
Define() [1/3]
bool ConfigGroupCollection::Define (const char * groupName) inline
Define a new empty group.
Define() [2/3]
void ConfigGroupCollection::Define (const char * groupName, const char * configName) inline
Define a configuration.
Define() [3/3]
void ConfigGroupCollection::Define (const char * groupName, const char * configName, const char * deviceLabel, const char * propName, const char * value) inline
Define a configuration property value.
Delete() [1/3]
bool ConfigGroupCollection::Delete (const char * groupName) inline
Delete an entire group.
Delete() [2/3]
bool ConfigGroupCollection::Delete (const char * groupName, const char * configName) inline
Delete a configuration from group
Delete() [3/3]
bool ConfigGroupCollection::Delete (const char * groupName, const char * configName, const char * deviceLabel, const char * propName) inline
Delete a property from a configuration in the specified group
Find()
Configuration* ConfigGroupCollection::Find (const char * groupName, const char * configName) inline
Finds preset (configuration) based on the group and preset names.
Referenced by CMMCore::isConfigDefined().
GetAvailableConfigs()
std::vector<std::string> ConfigGroupCollection::GetAvailableConfigs (const char * groupName) const inline
Returns a list of preset names.
Referenced by CMMCore::getAvailableConfigs().
GetAvailableGroups()
std::vector<std::string> ConfigGroupCollection::GetAvailableGroups () const inline
Returns a list of groups names.
Referenced by CMMCore::getAvailableConfigGroups().
isDefined()
bool ConfigGroupCollection::isDefined (const char * groupName) inline
Checks if group exists.
Referenced by CMMCore::isGroupDefined().
RenameConfig()
bool ConfigGroupCollection::RenameConfig (const char * groupName, const char * oldConfigName, const char * newConfigName) inline
Rename a configuration preset within a group
RenameGroup()
bool ConfigGroupCollection::RenameGroup (const char * oldGroupName, const char * newGroupName) inline
Rename a configuration group.
The documentation for this class was generated from the following file:
ConfigGroup.h