MMCore: PropertyBlock Class Reference
PropertyBlock Class Reference
#include <Configuration.h>
Public Member Functions
void addPair (const PropertyPair &pair)
PropertyPair getPair (size_t index) const throw (CMMError)
size_t size () const
std::string getValue (const char *key) const throw (CMMError)
Detailed Description
Encapsulation of the property collection. Designed to be wrapped by SWIG. A collection of property pairs.
Member Function Documentation
addPair()
void PropertyBlock::addPair (const PropertyPair & pair)
Adds a new pair to the current contents.
References PropertyPair::getPropertyName().
getPair()
PropertyPair PropertyBlock::getPair (size_t index) const throw (CMMError)
Returns the property pair with specified index.
Referenced by CMMCore::saveSystemConfiguration().
getValue()
std::string PropertyBlock::getValue (const char * key) const throw (CMMError)
Get value of the specified key (property).
size()
size_t PropertyBlock::size () const inline
Returns the number of contained property parts.
Referenced by CMMCore::saveSystemConfiguration().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp