MMCore: Configuration Class Reference
Configuration Class Reference
#include <Configuration.h>
Public Member Functions
void addSetting (const PropertySetting &setting)
void deleteSetting (const char *device, const char *prop)
bool isPropertyIncluded (const char *device, const char *property)
bool isSettingIncluded (const PropertySetting &ps)
bool isConfigurationIncluded (const Configuration &cfg)
PropertySetting getSetting (size_t index) const throw (CMMError)
PropertySetting getSetting (const char *device, const char *prop)
size_t size () const
std::string getVerbose () const
Detailed Description
Encapsulation of the configuration information. Designed to be wrapped by SWIG. A collection of configuration settings.
Member Function Documentation
addSetting()
void Configuration::addSetting (const PropertySetting & setting)
Adds new property setting to the existing contents.
Referenced by CMMCore::getConfigState(), CMMCore::getCurrentPixelSizeConfig(), CMMCore::getSystemState(), CoreCallback::OnPropertyChanged(), and CMMCore::setAutoShutter().
deleteSetting()
void Configuration::deleteSetting (const char * device, const char * prop)
Removes property setting, specified by device and property names, from the configuration.
getSetting() [1/2]
PropertySetting Configuration::getSetting (const char * device, const char * prop)
Get the setting with specified device name and property name.
getSetting() [2/2]
PropertySetting Configuration::getSetting (size_t index) const throw (CMMError)
Returns the setting with specified index.
Referenced by CMMCore::getConfigState(), CMMCore::getCurrentPixelSizeConfig(), CMMCore::saveSystemConfiguration(), CMMCore::saveSystemState(), CMMCore::setSystemState(), and CMMCore::waitForConfig().
getVerbose()
std::string Configuration::getVerbose () const
Returns verbose description of the object's contents.
isConfigurationIncluded()
bool Configuration::isConfigurationIncluded (const Configuration & cfg)
Checks whether a configuration is included. Included means that all devices from the operand configuration are included and that settings match
Referenced by CMMCore::getCurrentConfig(), CMMCore::getCurrentConfigFromCache(), and CMMCore::getCurrentPixelSizeConfig().
isPropertyIncluded()
bool Configuration::isPropertyIncluded (const char * device, const char * prop)
Checks whether the property is included in the configuration.
Referenced by CMMCore::defineStateLabel(), CMMCore::getCurrentPixelSizeConfig(), and CoreCallback::OnPropertyChanged().
isSettingIncluded()
bool Configuration::isSettingIncluded (const PropertySetting & ps)
Checks whether the setting is included in the configuration.
References PropertySetting::getPropertyValue().
Referenced by CMMCore::defineStateLabel().
size()
size_t Configuration::size () const inline
Returns the number of settings.
Referenced by CMMCore::getConfigState(), CMMCore::getCurrentPixelSizeConfig(), CoreCallback::OnPropertyChanged(), CMMCore::saveSystemConfiguration(), CMMCore::saveSystemState(), CMMCore::setSystemState(), and CMMCore::waitForConfig().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp