MMCore: PropertyPair Struct Reference
PropertyPair Struct Reference
#include <Configuration.h>
Public Member Functions
PropertyPair (const char *prop, const char *value)
std::string getPropertyName () const
std::string getPropertyValue () const
Detailed Description
Property pair defined as doublet: property - value.
Constructor & Destructor Documentation
PropertyPair()
PropertyPair::PropertyPair (const char * prop, const char * value) inline
Constructor for the struct specifying the entire contents.
Parameters
prop
value
Member Function Documentation
getPropertyName()
std::string PropertyPair::getPropertyName () const inline
Returns the property name.
Referenced by PropertyBlock::addPair(), and CMMCore::saveSystemConfiguration().
getPropertyValue()
std::string PropertyPair::getPropertyValue () const inline
Returns the property value.
Referenced by CMMCore::saveSystemConfiguration().
The documentation for this struct was generated from the following file:
Configuration.h