MMCore: PropertySetting Struct Reference
PropertySetting Struct Reference
#include <Configuration.h>
Public Member Functions
PropertySetting (const char *deviceLabel, const char *prop, const char *value, bool readOnly=false)
std::string getDeviceLabel () const
std::string getPropertyName () const
bool getReadOnly () const
std::string getPropertyValue () const
std::string getKey () const
std::string getVerbose () const
bool isEqualTo (const PropertySetting &ps)
Static Public Member Functions
static std::string generateKey (const char *device, const char *prop)
Detailed Description
Property setting defined as triplet: device - property - value.
Constructor & Destructor Documentation
PropertySetting()
PropertySetting::PropertySetting (const char * deviceLabel, const char * prop, const char * value, bool readOnly = false) inline
Constructor for the struct specifying the entire contents.
Parameters
deviceLabel
prop
value
Member Function Documentation
getDeviceLabel()
std::string PropertySetting::getDeviceLabel () const inline
Returns the device label.
Referenced by CMMCore::getConfigState(), CMMCore::getCurrentPixelSizeConfig(), CMMCore::saveSystemConfiguration(), CMMCore::saveSystemState(), CMMCore::setSystemState(), and CMMCore::waitForConfig().
getPropertyName()
std::string PropertySetting::getPropertyName () const inline
Returns the property name.
Referenced by CMMCore::getConfigState(), CMMCore::getCurrentPixelSizeConfig(), CMMCore::saveSystemConfiguration(), CMMCore::saveSystemState(), and CMMCore::setSystemState().
getPropertyValue()
std::string PropertySetting::getPropertyValue () const inline
Returns the property value.
Referenced by CMMCore::getPropertyFromCache(), Configuration::isSettingIncluded(), CMMCore::saveSystemConfiguration(), CMMCore::saveSystemState(), and CMMCore::setSystemState().
getReadOnly()
bool PropertySetting::getReadOnly () const inline
Returns the read-only status.
Referenced by CMMCore::setSystemState().
getVerbose()
string PropertySetting::getVerbose () const
Returns verbose description of the object's contents.
The documentation for this struct was generated from the following files:
Configuration.h
Configuration.cpp